dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - bc
      - google-chrome-stable
      - wget

matrix:
  include:
    - language: python
      python:
        - "2.7"
      before_install:
        # Install bazel.
        - wget https://github.com/bazelbuild/bazel/releases/download/0.11.1/bazel_0.11.1-linux-x86_64.deb
        - echo f3df344b16a40d4233a7606cce38869d4df3bb35296ac2f4e18838566ae3cb48 bazel_0.11.1-linux-x86_64.deb | sha256sum -c
        - sudo dpkg -i bazel_0.11.1-linux-x86_64.deb
        - rm bazel_0.11.1-linux-x86_64.deb
      script:
        - ./backend_tests.sh $GROUP $TOTAL_GROUPS
    - language: node_js
      node_js:
        - "8.11.0"
      script:
        - ./angular_tests.sh


env:
  global:
    - TOTAL_GROUPS=4
  matrix:
    - GROUP=0
    - GROUP=1
    - GROUP=2
    - GROUP=3
